name: CI + CD

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches: [ develop ]
    types:
      - opened
      - synchronize
      - closed
  workflow_dispatch:

jobs:
  CodeAnalysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' || 
      (github.event_name == 'pull_request' && github.event.action == 'opened' )
    steps:
      - uses: actions/checkout@v4
      - name: code analysis
        run: echo code analysis    

  DeployEuDev:
    name: Deploy to eu-central-1/test
    runs-on: ubuntu-latest
    needs: [CodeAnalysis]
    if: >
      github.event_name == 'pull_request' &&
      (github.event.action == 'opened' || github.event.action == 'synchronize')
    steps:
      - name: Deploy
        run: echo I am deploying to Dev!        

  # DeployEuInt:
  #   name: Deploy to eu-central-1/Int 
  #   runs-on: ubuntu-latest
  #   needs: [Build]
  #   if: |
  #     github.event_name == 'pull_request' &&
  #     (github.event.action == 'opened' || github.event.action == 'synchronize') ||
  #     (github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main')
  #   environment: 
  #     name: eu_int
  #     url: 'http://eu_int.com'
  #   steps:
  #     - name: Deploy
  #       run: echo I am deploying to eu_int!

  # DeployEuE2e:
  #   name: Deploy to eu-central-1/e2e 
  #   runs-on: ubuntu-latest
  #   needs: [DeployEuInt]
  #   if: >
  #     github.event.action == 'closed' &&
  #     github.event.pull_request.merged == true &&
  #     github.ref == 'refs/heads/main'
  #   environment: 
  #     name: eu_e2e
  #     url: 'http://eu_e2e.com'
  #   steps:
  #     - name: Deploy
  #       run: echo I  am deploying to eu_e2e!

  # DeployUsE2e:
    # name: Deploy to us-east-1/e2e 
    # runs-on: ubuntu-latest
    # needs: [DeployEuInt]
    # if: >
    #   github.event.action == 'closed' &&
    #   github.event.pull_request.merged == true &&
    #   github.ref == 'refs/heads/main'
    # environment: 
    #   name: us_e2e
    #   url: 'http://us_e2e.com'
    # steps:
    #   - name: Deploy
    #     run: echo I  am deploying to us_e2e!

#   reusable:
#     uses: eduardogobetti/reusable_workflow/.github/workflows/say_hello.yml@main
#     with:
#       nome: Ernesto        