name: Minor Tag

on:
  pull_request:
    branches: [ develop ]
    types:
      - opened
      - synchronize
      - closed
  workflow_dispatch:
jobs:
  # criar a tag na develop se o a pr for concluida 
  TagEuDev: 
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && 
            github.event.action == 'closed' && 
            github.event.pull_request.merged == true && 
            github.event.pull_request.base.ref == 'develop' &&
            startsWith(github.event.pull_request.head.ref, 'release/') }}
    permissions:
      contents: write            
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          DEFAULT_BUMP: minor
          WITH_V: false
          PRERELEASE: false